require 'spree_core'
require 'spree_shared/engine'
require 'apartment'
require 'spree_shared/apartment_elevator'
require 'spree_shared/action_view_extensions'
require 'spree_shared/deface_extensions'
require 'spree_shared/spree_preferences_extensions'
